### ISSUE TITLE
wkhtmltopdf-binary gem won't install on debian stable

### ISSUE THREAD

**Issue by munen** [huerlisi/bookyt#23]
Hi Simon

I'm running current Debian stable (7.3) and wkhtmltopdf-binary will not install. Since this is kind of a weird gem (really just providing a binary?) I tried installing wkhtmltopdf as Debian package and made sure the path is correct in the config. However, neither balance sheet nor profit sheet will render as PDF as the command wkhtmltopdf will try to do something forever and never return, but it does get called! I also did make sure to install exactly 0.9.9.1 as current Debian stable provides 0.9.9.4.

Best regards
Munen Alain

    ➜  bookyt git:(master) ✗ gem install wkhtmltopdf-binary -v '0.9.9.1'
    WARNING:  Error fetching data: SocketError: getaddrinfo: Name or service not known     
    (http://production.cf.rubygems.org/specs.4.8.gz)
    ERROR:  Error installing wkhtmltopdf-binary:
        	invalid gem format for /home/munen/.rbenv/versions/1.9.3-    p448/lib/ruby/gems/1.9.1/cache/wkhtmltopdf-binary-0.9.9.1.gem

**Comment by huerlisi** [comment]
Should be fixed. Both by the port and Prawn, and in 38ef2f7 otherwise.

A new Debian is released anyway;-)

Closing, please reopen if the issue persists.
