### ISSUE TITLE
Migration on a Fresh Install raises an Error

### ISSUE THREAD

**Issue by silvermind** [huerlisi/bookyt#47]
using master with mysql in DEVELOPMENT I got this error during the migrations:

FixInvoicePaymentAccountTag: migrating
rake aborted!
**StandardError: An error has occurred, all later migrations canceled:**

undefined method `tagged_with' for #<Class:0x000000056dec00>/home/sev/.rvm/gems/ruby-2.1.4/gems/activerecord-3.2.21/lib/active_record/dynamic_matchers.rb:55:in `method_missing'
/home/sev/src/silvermind/bookyt/db/migrate/20150218105255_fix_invoice_payment_account_tag.rb:3:in `up'

this line failes:
account = Account.tagged_with('invoice_payment').where(code: '1020').first

**Comment by huerlisi** [comment]
Working on it right now:-)

Expect a fix in the next couple of minutes.

**Comment by huerlisi** [comment]
Fixed in ee2556e.
