### ISSUE TITLE
Precompile Task in Rails Asset Pipeline fails with Sass::SyntaxError on master

### ISSUE THREAD

**Issue by silvermind** [huerlisi/bookyt#49]
When using capistrano 3 to deploy, the asset precompile task fails with a Syntax Error:

Sass::SyntaxError: Properties are only allowed within rules, directives, mixin includes, or other properties.
  (in /home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/has_accounts_engine-3.0.0.beta5/app/assets/stylesheets/has_accounts_engine/screen.scss)

may be an issue in the has_accounts_engine gem

https://github.com/huerlisi/has_accounts_engine/blob/a6075f73ebf2ca8735dbdc6c63a3426026a969a9/app/assets/stylesheets/has_accounts_engine/partials/content/_overview.sass#L36

@huerlisi Do you know if the comment and the nesting on the same line is allowed in SCSS, this may be the issue..?

# Stack Trace
rake stderr: /home/silvermind_bookyt/.rbenv/versions/2.1.6/bin/ruby /home/silvermind_bookyt/shared/bundle/ruby/2.1.0/bin/rake assets:precompile:all RAILS_ENV=production RAILS_GROUPS=assets
rake aborted!
Sass::SyntaxError: Properties are only allowed within rules, directives, mixin includes, or other properties.
  (in /home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/has_accounts_engine-3.0.0.beta5/app/assets/stylesheets/has_accounts_engine/screen.scss)
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/has_accounts_engine-3.0.0.beta5/app/assets/stylesheets/has_accounts_engine/partials/content/_overview.sass:36
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/has_accounts_engine-3.0.0.beta5/app/assets/stylesheets/has_accounts_engine/screen.scss:5
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/check_nesting.rb:13:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `map'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/check_nesting.rb:49:in `visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:38:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/check_nesting.rb:15:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `map'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/check_nesting.rb:49:in `visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:38:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/check_nesting.rb:15:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `map'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/check_nesting.rb:49:in `visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:38:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/check_nesting.rb:15:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `map'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/check_nesting.rb:49:in `visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/check_nesting.rb:57:in `visit_root'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/check_nesting.rb:15:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:24:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:324:in `block in visit_import'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/stack.rb:88:in `block in with_import'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/stack.rb:88:in `with_import'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/stack.rb:79:in `block in with_base'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/stack.rb:79:in `with_base'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `map'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:157:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/visitors/perform.rb:8:in `visit'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/root_node.rb:36:in `css_tree'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/tree/root_node.rb:20:in `render'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-3.4.13/lib/sass/engine.rb:268:in `render'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sass-rails-3.2.6/lib/sass/rails/template_handlers.rb:106:in `evaluate'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/context.rb:193:in `block in evaluate'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/context.rb:190:in `each'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/context.rb:190:in `evaluate'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/processed_asset.rb:12:in `initialize'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:249:in `new'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:249:in `block in build_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:270:in `circular_call_protection'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:248:in `build_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:93:in `block in build_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/caching.rb:19:in `cache_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:92:in `build_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:169:in `find_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:60:in `find_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/processed_asset.rb:105:in `each'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/processed_asset.rb:16:in `initialize'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:249:in `new'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:249:in `block in build_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:270:in `circular_call_protection'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:248:in `build_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:93:in `block in build_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/caching.rb:19:in `cache_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:92:in `build_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:169:in `find_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:60:in `find_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/bundled_asset.rb:16:in `initialize'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:252:in `new'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:252:in `build_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:93:in `block in build_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/caching.rb:19:in `cache_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:92:in `build_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:169:in `find_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/index.rb:60:in `find_asset'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/sprockets/static_compiler.rb:19:in `block in compile'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:219:in `block in each_logical_path'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:206:in `block (2 levels) in each_file'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:196:in `each'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:196:in `each_entry'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:204:in `block in each_file'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:203:in `each'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:203:in `each_file'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/sprockets-2.2.3/lib/sprockets/base.rb:217:in `each_logical_path'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/sprockets/static_compiler.rb:18:in `compile'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/sprockets/assets.rake:56:in `internal_precompile'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/sprockets/assets.rake:70:in `block (3 levels) in <top (required)>'
/home/silvermind_bookyt/shared/bundle/ruby/2.1.0/gems/actionpack-3.2.21/lib/sprockets/assets.rake:60:in `block (3 levels) in <top (required)>'
Tasks: TOP => assets:precompile:primary

**Comment by huerlisi** [comment]
Should be fixed.
